### PR TITLE
Upated-with-analyzer-4.6.0

### PR DESCRIPTION
**Pull request by ashutosh2014**
Fix https://github.com/google/reflectable.dart/issues/286

### CODE REVIEW

**Comment by zmeggyesi** [comment]
Can we get this merged and released? It looks like the current package is hopelessly broken on Dart 2.18, and this needs to be edited by hand.

CC @eernstg , perhaps?

**Review by eernstg — APPROVED** [review]
Very good! This enables usage right now. The resulting package has 86 usages of a deprecated API, but I'm fixing that in #288.

**Comment by eernstg** [comment]
@ashutosh2014, could you provide the CLA?

**Comment by ashutosh2014** [comment]
Hi @eernstg, Thanks for the review I have provided CLA Please feel free to merge it.

**Pull request merged**
